server:
  port: 9999

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/project
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.project.user.dto

logging:
  level:
    org.springframework.security: DEBUG
    org.mybatis.spring: TRACE
    com.project.project.user.mapper: DEBUG

file:
  location: /Users/sujeong/Documents/workspace/upload

servlet:
  multipart:
    enabled: true
    max-file-size: 20MB  # 최대 파일 크기 설정
    max-request-size: 20MB  # 최대 요청 크기 설정